; RejsaCAN-ESP32-S3 v3.4 — Tesla CAN コントロールシステム
; ============================================================

[env:rejsacan-esp32s3]
platform   = espressif32
board      = esp32-s3-devkitc-1
framework  = arduino

monitor_speed   = 115200
monitor_filters =
    esp32_exception_decoder
    colorize

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    ESP Async WebServer     ; WiFi HTTP + WebSocket

lib_ignore =
    AsyncTCP_RP2040W
